<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="entity" nsURI="http://www.lunifera.org/dsl/entity/v1" nsPrefix="entity">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="fileExtensions" value="entitymodel"/>
    <details key="modelName" value="Entity"/>
    <details key="prefix" value="Entity"/>
    <details key="basePackage" value="org.lunifera.dsl.semantic"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="rootPackage" value="entity"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="LEntityModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="ecore:EClass ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LTypedPackage"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LBean" eSuperTypes="../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LClass ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LScalarType ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LFeaturesHolder">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*&#xA;A bean is an embeddable element that may become added to a entity using the @embedd annotation."/>
    </eAnnotations>
    <eOperations name="getOperations" unique="false" eType="#//OperationsList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of type LOperation"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getReferences" unique="false" eType="#//BeanReferenceList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of type LBeanReference"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAttributes" unique="false" eType="#//BeanAttributeList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of type LBeanAttribute"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllFeatures" unique="false" eType="#//BeanFeatureList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of the holder and from super types"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllAttributes" unique="false" eType="#//BeanAttributeList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all attributes of the holder and from super types"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllReferences" unique="false" eType="#//BeanReferenceList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all references of the holder and from super types"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="collectAllLunFeatures" unique="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value=""/>
      </eAnnotations>
      <eParameters name="current" unique="false" eType="#//LBean"/>
      <eParameters name="result" unique="false" eType="#//BeanFeatureList"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//LBeanFeature" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//LBean"
        resolveProxies="false" eOpposite="#//LBean/subTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
        eType="#//LBean" transient="true" eOpposite="#//LBean/superType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LEntity" eSuperTypes="../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LClass ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LFeaturesHolder">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*&#xA;Represents a JPA entity."/>
    </eAnnotations>
    <eOperations name="getOperations" unique="false" eType="#//OperationsList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of type LOperation"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getReferences" unique="false" eType="#//EntityReferenceList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of type LEntityReference"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAttributes" unique="false" eType="#//EntityAttributeList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of type LEntityAttribute"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllFeatures" unique="false" eType="#//EntityFeatureList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of the holder and from super types"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllAttributes" unique="false" eType="#//EntityAttributeList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all attributes of the holder and from super types"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllReferences" unique="false" eType="#//EntityReferenceList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all references of the holder and from super types"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="collectAllLunFeatures" unique="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value=""/>
      </eAnnotations>
      <eParameters name="current" unique="false" eType="#//LEntity"/>
      <eParameters name="result" unique="false" eType="#//EntityFeatureList"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheable" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="historized" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappedSuperclass" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistenceInfo" eType="#//LEntityPersistenceInfo"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritanceStrategy" eType="#//LEntityInheritanceStrategy"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//LEntityFeature" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//LIndex" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//LEntity"
        resolveProxies="false" eOpposite="#//LEntity/subTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
        eType="#//LEntity" transient="true" eOpposite="#//LEntity/superType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LEntityPersistenceInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaName" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LEntityColumnPersistenceInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnName" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LEntityInheritanceStrategy" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="LTablePerClassStrategy" eSuperTypes="#//LEntityInheritanceStrategy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorColumn" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorType" unique="false"
        eType="#//LDiscriminatorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LTablePerSubclassStrategy" eSuperTypes="#//LEntityInheritanceStrategy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorColumn" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorType" unique="false"
        eType="#//LDiscriminatorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LDiscriminatorType">
    <eLiterals name="INHERIT"/>
    <eLiterals name="STRING"/>
    <eLiterals name="CHAR"/>
    <eLiterals name="INTEGER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LEntityFeature" eSuperTypes="../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LFeature">
    <eOperations name="getEntity" unique="false" eType="#//LEntity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistenceInfo" eType="#//LEntityColumnPersistenceInfo"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LEntityAttribute" eSuperTypes="#//LEntityFeature ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LEntityReference" eSuperTypes="#//LEntityFeature ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//LEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//LEntityReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LBeanFeature" eSuperTypes="../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LFeature">
    <eOperations name="getBean" unique="false" eType="#//LBean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LBeanAttribute" eSuperTypes="#//LBeanFeature ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="LBeanReference" eSuperTypes="#//LBeanFeature ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//LBean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//LBeanReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LIndex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//LEntityFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LOperation" eSuperTypes="../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LOperation #//LBeanFeature #//LEntityFeature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*&#xA;Overwrites LOperation to add bean and entity feature as supertype"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OperationsList" instanceTypeName="java.util.List&lt;void>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EntityFeatureList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.entity.LEntityFeature>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EntityReferenceList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.entity.LEntityReference>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EntityAttributeList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.entity.LEntityAttribute>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeanFeatureList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.entity.LBeanFeature>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeanReferenceList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.entity.LBeanReference>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeanAttributeList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.entity.LBeanAttribute>"/>
</ecore:EPackage>
