/*
 * generated by Xtext
 */
package org.lunifera.dsl.datatype.xtext.formatting;

import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.lunifera.dsl.common.xtext.formatting.CommonGrammarFormatter;
import org.lunifera.dsl.common.xtext.services.CommonGrammarGrammarAccess.ClassElements;
import org.lunifera.dsl.common.xtext.services.CommonGrammarGrammarAccess.ImportElements;
import org.lunifera.dsl.datatype.xtext.services.DatatypeGrammarGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an
 * example
 */
public class DatatypeGrammarFormatter extends CommonGrammarFormatter {

	@Override
	protected void configureFormatting(FormattingConfig c) {
		configure(c, (DatatypeGrammarGrammarAccess) getGrammarAccess());
	}

	public void configure(FormattingConfig c, DatatypeGrammarGrammarAccess ga) {
		DatatypeGrammarGrammarAccess f = (DatatypeGrammarGrammarAccess) getGrammarAccess();

		super.configure(c, ga.getCommonGrammarGrammarAccess());

		configurePackageDef(c, f.getTypedPackageAccess());

		c.setLinewrap(0, 1, 2).before(f.getSL_COMMENTRule());
		c.setLinewrap(0, 1, 2).after(f.getSL_COMMENTRule());
		c.setLinewrap(0, 1, 2).before(f.getML_COMMENTRule());
		c.setLinewrap(1, 1, 1).after(f.getML_COMMENTRule());

		for (Keyword kw : ga.findKeywords("@")) {
			c.setNoSpace().after(kw);
		}
		for (Keyword kw : ga.findKeywords("(")) {
			c.setNoSpace().after(kw);
		}
		for (Keyword kw : ga.findKeywords("(")) {
			c.setNoSpace().before(kw);
		}
		for (Keyword kw : ga.findKeywords(")")) {
			c.setNoSpace().before(kw);
		}
		for (Keyword kw : ga.findKeywords(";")) {
			c.setNoSpace().before(kw);
		}
		for (Keyword kw : ga.findKeywords(",")) {
			c.setNoSpace().before(kw);
		}
	}
	

	protected void configurePackageDef(FormattingConfig c,
			DatatypeGrammarGrammarAccess.TypedPackageElements ele) {

		c.setLinewrap().around(ele.getRule());
		
		c.setIndentationIncrement().after(ele.getLeftCurlyBracketKeyword_3_0());
		
		c.setLinewrap(1).before(ele.getRightCurlyBracketKeyword_3_3());
		c.setIndentationDecrement().before(ele.getRightCurlyBracketKeyword_3_3());
	}



}
