/**
 * Copyright (c) 2011 - 2012, Florian Pirchner - lunifera.org
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Sources generated by Xtext  
 * 
 * Contributors:
 *  		Florian Pirchner - Initial implementation
 */
package org.lunifera.dsl.entity.xtext.extensions;

public interface Constants {
	public static final String BUILTINT_COMPILER_PACKAGE = "org.lunifera.annotation.processor";
	public static final String POJO_COMPILER_NAME = "Pojo";
	public static final String POJO_COMPILER_FQN = BUILTINT_COMPILER_PACKAGE
			+ "." + POJO_COMPILER_NAME;
	public static final String JPA_COMPILER_NAME = "JPA";
	public static final String JPA_COMPILER_FQN = BUILTINT_COMPILER_PACKAGE
			+ "." + JPA_COMPILER_NAME;

	/**
	 * Is used to name guice annotations. Impls of that type will dispatch the
	 * calls to targets.
	 */
	public static final String DELEGATE = "delegate";

}
