/*
 * generated by Xtext
 */
package org.lunifera.dsl.dto.xtext.ui.outline;

import org.lunifera.dsl.semantic.dto.LDtoAbstractReference;
import org.lunifera.dsl.semantic.dto.LDtoMapper;
import org.lunifera.dsl.semantic.dto.impl.LDtoAbstractAttributeImpl;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
public class DtoGrammarOutlineTreeProvider extends
		org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {

	/**
	 * Default for isLeafDispatcher
	 */
	protected boolean _isLeaf(LDtoMapper mapper) {
		return true;
	}

	/**
	 * Default for isLeafDispatcher
	 */
	protected boolean _isLeaf(LDtoAbstractReference element) {
		return element.getMapper() == null;
	}

	/**
	 * Default for isLeafDispatcher
	 */
	protected boolean _isLeaf(LDtoAbstractAttributeImpl element) {
		return element.getMapper() == null;
	}

}
