/*
* generated by Xtext
*/
package org.lunifera.dsl.common.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CommonGrammarStandaloneSetup extends CommonGrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new CommonGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

