/*
* generated by Xtext
*/
package org.lunifera.dsl.services.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ServicesGrammarStandaloneSetup extends ServicesGrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new ServicesGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

