/**
 * Copyright (c) 2011 - 2014, Lunifera GmbH (Gross Enzersdorf), Loetz KG (Heidelberg)
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors: 
 * 		Florian Pirchner - Initial implementation
 */



/*
 * generated by Xtext
 */
package org.lunifera.dsl.datatype.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;



/**
 * Use this class to register components to be used within the IDE.
 */
public class DatatypeGrammarUiModule extends org.lunifera.dsl.datatype.xtext.ui.AbstractDatatypeGrammarUiModule {
	public DatatypeGrammarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
