/*
 * generated by Xtext
 */
package org.lunifera.dsl.datatype.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DatatypeGrammarUiModule extends org.lunifera.dsl.datatype.xtext.ui.AbstractDatatypeGrammarUiModule {
	public DatatypeGrammarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
