/**
 * Copyright (c) 2011 - 2013, Committers of lunifera.org
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Sources generated by Xtext  
 * 
 * Contributors:
 *  		Cristiano Gaviao - Initial implementation
 */
package org.lunifera.dsl.organization.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class OrganizationGrammarStandaloneSetup extends OrganizationGrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new OrganizationGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

