/**
 *
 * $Id$
 */
package org.lunifera.dsl.xtext.cache.model.validation;

import org.eclipse.emf.common.util.EList;

import org.lunifera.dsl.xtext.cache.model.XCLogicalContainer;
import org.lunifera.dsl.xtext.cache.model.XCSourceToTarget;
import org.lunifera.dsl.xtext.cache.model.XCTargetToSource;

/**
 * A sample validator interface for {@link org.lunifera.dsl.xtext.cache.model.XCJvmModelAssociation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XCJvmModelAssociationValidator {
	boolean validate();

	boolean validateSourceToTargets(EList<XCSourceToTarget> value);
	boolean validateTargetToSources(EList<XCTargetToSource> value);
	boolean validateLocalContainers(EList<XCLogicalContainer> value);
}
