/*
 * generated by Xtext
 */
package org.lunifera.dsl.entity.xtext;

import org.eclipse.xtext.scoping.IScopeProvider;
import org.lunifera.dsl.entity.xtext.extensions.Constants;
import org.lunifera.dsl.entity.xtext.jvmmodel.DelegatingAnnotationCompiler;
import org.lunifera.dsl.entity.xtext.jvmmodel.DelegatingOperationContentCompiler;
import org.lunifera.dsl.entity.xtext.jvmmodel.EntityJvmModelGenerator;
import org.lunifera.dsl.entity.xtext.jvmmodel.services.IAnnotationCompiler;
import org.lunifera.dsl.entity.xtext.jvmmodel.services.IEntityJvmModelInferrerDelegate;
import org.lunifera.dsl.entity.xtext.jvmmodel.services.IOperationContentCompiler;
import org.lunifera.dsl.entity.xtext.jvmmodel.services.entity.PojoAnnotationCompiler;
import org.lunifera.dsl.entity.xtext.jvmmodel.services.entity.PojoJvmModelInferrerDelegate;
import org.lunifera.dsl.entity.xtext.jvmmodel.services.entity.PojoOperationsGenerator;
import org.lunifera.dsl.entity.xtext.jvmmodel.services.jpa.JPAAnnotationCompiler;
import org.lunifera.dsl.entity.xtext.jvmmodel.services.jpa.JPAJvmModelInferrerDelegate;
import org.lunifera.dsl.entity.xtext.jvmmodel.services.jpa.JPAOperationsGenerator;
import org.lunifera.dsl.entity.xtext.scope.EntityImportedNamespaceAwareLocalScopeProvider;
import org.lunifera.dsl.entity.xtext.scope.EntityScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class EntityGrammarRuntimeModule extends
		org.lunifera.dsl.entity.xtext.AbstractEntityGrammarRuntimeModule {
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return org.lunifera.dsl.entity.xtext.valueconverter.EntityQualifiedNameProvider.class;
	}

	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return EntityScopeProvider.class;
	}

	@Override
	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named("org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.delegate"))
				.to(EntityImportedNamespaceAwareLocalScopeProvider.class);
	}

	// contributed by org.eclipse.xtext.generator.xbase.XbaseGeneratorFragment
	public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
		return EntityJvmModelGenerator.class;
	}

	/**
	 * The modelInferrer delegate to be used for entity compiles.
	 * 
	 * @param binder
	 */
	public void configurePojoJvmModelInferrerDelegate(
			com.google.inject.Binder binder) {
		binder.bind(IEntityJvmModelInferrerDelegate.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named(Constants.POJO_COMPILER_FQN))
				.to(PojoJvmModelInferrerDelegate.class);
	}

	/**
	 * The modelInferrer delegate to be used for JPA compiles.
	 * 
	 * @param binder
	 */
	public void configureJPAJvmModelInferrerDelegate(
			com.google.inject.Binder binder) {
		binder.bind(IEntityJvmModelInferrerDelegate.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named(Constants.JPA_COMPILER_FQN))
				.to(JPAJvmModelInferrerDelegate.class);
	}

	/**
	 * The operationsContentCompiler to be used to dispatch the calles.
	 * 
	 * @param binder
	 */
	public void configureDelegateOperationsCompiler(
			com.google.inject.Binder binder) {
		binder.bind(IOperationContentCompiler.class)
				.annotatedWith(
						com.google.inject.name.Names.named(Constants.DELEGATE))
				.to(DelegatingOperationContentCompiler.class);
	}

	/**
	 * The operationsContentCompiler to be used for entity compiles.
	 * 
	 * @param binder
	 */
	public void configurePojoOperationsCompiler(com.google.inject.Binder binder) {
		binder.bind(IOperationContentCompiler.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named(Constants.POJO_COMPILER_FQN))
				.to(PojoOperationsGenerator.class);
	}

	/**
	 * The operationsContentCompiler to be used for JPA compiles.
	 * 
	 * @param binder
	 */
	public void configureJPAOperationsCompiler(com.google.inject.Binder binder) {
		binder.bind(IOperationContentCompiler.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named(Constants.JPA_COMPILER_FQN))
				.to(JPAOperationsGenerator.class);
	}

	/**
	 * The annotationCompiler to be used to dispatch the calles.
	 * 
	 * @param binder
	 */
	public void configureDelegateAnnotationCompiler(
			com.google.inject.Binder binder) {
		binder.bind(IAnnotationCompiler.class)
				.annotatedWith(
						com.google.inject.name.Names.named(Constants.DELEGATE))
				.to(DelegatingAnnotationCompiler.class);
	}

	/**
	 * The annotationCompiler to be used for pojo compiles.
	 * 
	 * @param binder
	 */
	public void configurePojoAnnotationCompiler(com.google.inject.Binder binder) {
		binder.bind(IAnnotationCompiler.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named(Constants.POJO_COMPILER_FQN))
				.to(PojoAnnotationCompiler.class);
	}

	/**
	 * The annotationCompiler to be used for jpa compiles.
	 * 
	 * @param binder
	 */
	public void configureJPAAnnotationCompiler(com.google.inject.Binder binder) {
		binder.bind(IAnnotationCompiler.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named(Constants.JPA_COMPILER_FQN))
				.to(JPAAnnotationCompiler.class);
	}
}
