/*******************************************************************************
 * Copyright (c) 2011, 2012 Cristiano Gavião - Lunifera.org.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Cristiano Gavião - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.lunifera.dsl.organization.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.label.StylerFactory;
import org.lunifera.dsl.organization.semantic.model.BusinessRole;
import org.lunifera.dsl.organization.semantic.model.Group;
import org.lunifera.dsl.organization.semantic.model.Organization;
import org.lunifera.dsl.organization.semantic.model.OrganizationUnit;
import org.lunifera.dsl.organization.semantic.model.Partnership;
import org.lunifera.dsl.organization.semantic.model.Person;
import org.lunifera.dsl.organization.semantic.model.Worker;

import com.google.inject.Inject;

/**
 * customization of the default outline structure
 */
public class OrganizationGrammarOutlineTreeProvider extends
		DefaultOutlineTreeProvider {

	@Inject
	private StylerFactory stylerFactory;

	private VirtualOutlineNode personsGroup;
	private VirtualOutlineNode groupsGroup;
	private VirtualOutlineNode bRolesGroup;
	private VirtualOutlineNode partenershipsGroup;
	private VirtualOutlineNode unitsGroup;
	private VirtualOutlineNode workersGroup;

	/**
	 * Skip the root node.
	 * 
	 * @param parentNode
	 * @param model
	 */
	protected void _createChildren(IOutlineNode parentNode,
			Organization organization) {
		for (Person element : organization.getPersons()) {
			createNode(getPersonGroup(parentNode), element);
		}
		for (Group element : organization.getGroups()) {
			createNode(getGroupsGroup(parentNode), element);
		}
		for (Partnership element : organization.getPartnerships()) {
			createNode(getPartnershipsGroup(parentNode), element);
		}
		for (BusinessRole element : organization.getRoles()) {
			createNode(getRolesGroup(parentNode), element);
		}
		for (OrganizationUnit element : organization.getUnits()) {
			createNode(getUnitsGroup(parentNode), element);
		}
		for (Worker element : organization.getWorkers()) {
			createNode(getWorkersGroup(parentNode), element);
		}
	}

	public VirtualOutlineNode getPersonGroup(IOutlineNode parentNode) {
		if (personsGroup == null) {
			personsGroup = new VirtualOutlineNode(parentNode, null, "Persons",
					false);
		}
		return personsGroup;
	}
	public VirtualOutlineNode getGroupsGroup(IOutlineNode parentNode) {
		if (groupsGroup == null) {
			groupsGroup = new VirtualOutlineNode(parentNode, null, "Groups",
					false);
		}
		return groupsGroup;
	}
	public VirtualOutlineNode getRolesGroup(IOutlineNode parentNode) {
		if (bRolesGroup == null) {
			bRolesGroup = new VirtualOutlineNode(parentNode, null, "Roles",
					false);
		}
		return bRolesGroup;
	}
	public VirtualOutlineNode getUnitsGroup(IOutlineNode parentNode) {
		if (unitsGroup == null) {
			unitsGroup = new VirtualOutlineNode(parentNode, null, "Units",
					false);
		}
		return unitsGroup;
	}
	public VirtualOutlineNode getPartnershipsGroup(IOutlineNode parentNode) {
		if (partenershipsGroup == null) {
			partenershipsGroup = new VirtualOutlineNode(parentNode, null, "Partnerships",
					false);
		}
		return partenershipsGroup;
	}
	public VirtualOutlineNode getWorkersGroup(IOutlineNode parentNode) {
		if (workersGroup == null) {
			workersGroup = new VirtualOutlineNode(parentNode, null, "Workers",
					false);
		}
		return workersGroup;
	}

}
