/*
* generated by Xtext
*/
package org.lunifera.dsl.dto.xtext.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.lunifera.dsl.dto.xtext.services.DtoGrammarGrammarAccess;

import com.google.inject.Inject;

public class DtoGrammarParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DtoGrammarGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.lunifera.dsl.dto.xtext.parser.antlr.internal.InternalDtoGrammarParser createParser(XtextTokenStream stream) {
		return new org.lunifera.dsl.dto.xtext.parser.antlr.internal.InternalDtoGrammarParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LDTOModel";
	}
	
	public DtoGrammarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DtoGrammarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
