/*
* generated by Xtext
*/
package org.lunifera.dsl.datatype.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DatatypeGrammarAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/lunifera/dsl/datatype/xtext/parser/antlr/internal/InternalDatatypeGrammar.tokens");
	}
}
