/*
* generated by Xtext
*/
package org.lunifera.dsl.datatype.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.lunifera.dsl.datatype.xtext.services.DatatypeGrammarGrammarAccess;

public class DatatypeGrammarParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DatatypeGrammarGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.lunifera.dsl.datatype.xtext.parser.antlr.internal.InternalDatatypeGrammarParser createParser(XtextTokenStream stream) {
		return new org.lunifera.dsl.datatype.xtext.parser.antlr.internal.InternalDatatypeGrammarParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LCommonModel";
	}
	
	public DatatypeGrammarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DatatypeGrammarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
