/*
* generated by Xtext
*/
package org.lunifera.dsl.dto.xtext.ui.quickfix;

/**
 * Custom quickfixes.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
public class DtoGrammarQuickfixProvider extends org.eclipse.xtext.xbase.annotations.ui.quickfix.XbaseWithAnnotationsQuickfixProvider {



}
