/*******************************************************************************
 * Copyright (c) 2011, 2012 Cristiano Gavião - Lunifera.org.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Cristiano Gavião - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.lunifera.dsl.organization.xtext.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.lunifera.dsl.organization.semantic.model.BusinessRole;
import org.lunifera.dsl.organization.semantic.model.Group;
import org.lunifera.dsl.organization.semantic.model.Organization;
import org.lunifera.dsl.organization.semantic.model.OrganizationUnit;
import org.lunifera.dsl.organization.semantic.model.OrganizationUnitType;
import org.lunifera.dsl.organization.semantic.model.Partnership;
import org.lunifera.dsl.organization.semantic.model.Person;
import org.lunifera.dsl.organization.semantic.model.Worker;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class OrganizationGrammarLabelProvider extends
		DefaultEObjectLabelProvider {

	@Inject
	IQualifiedNameProvider nameProvider;
	
	@Inject
	public OrganizationGrammarLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String image(Organization ele){
		return "organization.png";
	}
	
	String image(OrganizationUnit ele){
		return "organizationunit.png";
	}
	
	String image(Person ele){
		return "person.png";
	}
	
	String image(Worker ele){
		return "worker.png";
	}
	
	String image(Group ele){
		return "group.png";
	}
	
	String image(BusinessRole ele){
		return "role.png";
	}
	
	String image(Partnership ele){
		return "partnership.png";
	}
	
	String image(OrganizationUnitType ele){
		return "organizationunittype.png";
	}
	

	public Object text(Worker element) {
		return nameProvider.getFullyQualifiedName(element).getLastSegment();
	}

	public Object text(Partnership element) {
		return nameProvider.getFullyQualifiedName(element).getLastSegment();
	}
}
