<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dto" nsURI="http://www.lunifera.org/dsl/dto/v1" nsPrefix="dto">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="fileExtensions" value="dtomodel"/>
    <details key="modelName" value="DTO"/>
    <details key="prefix" value="Dto"/>
    <details key="basePackage" value="org.lunifera.dsl.semantic"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="rootPackage" value="dto"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="LDtoModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="ecore:EClass ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LTypedPackage"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDto" eSuperTypes="../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LClass ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LFeaturesHolder ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LScalarType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*&#xA;A bean is an embeddable element that may become added to a entity using the @embedd annotation."/>
    </eAnnotations>
    <eOperations name="getOperations" unique="false" eType="#//OperationsList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of type LOperation"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getReferences" unique="false" eType="#//DtoReferenceList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of type LDtoReference"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAttributes" unique="false" eType="#//DtoAttributeList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of type LDtoAttribute"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllFeatures" unique="false" eType="ecore:EDataType ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/FeaturesList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Returns all features of the holder and from super types"/>
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="collectAllLunFeatures" unique="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value=""/>
      </eAnnotations>
      <eParameters name="current" unique="false" eType="#//LDto"/>
      <eParameters name="result" unique="false" eType="#//DtoFeatureList"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//LDtoFeature" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//LDto"
        resolveProxies="false" eOpposite="#//LDto/subTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
        eType="#//LDto" transient="true" eOpposite="#//LDto/superType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wrappedType" eType="ecore:EClass ../../org.lunifera.dsl.semantic.entity/model/entity.xcore#/EPackage/LEntity"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDtoFeature" eSuperTypes="../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LFeature">
    <eOperations name="getDTO" unique="false" eType="#//LDto">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value=""/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inherit" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDtoAttribute" eSuperTypes="#//LDtoFeature ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toDTO" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromDTO" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedFeature" eType="ecore:EClass ../../org.lunifera.dsl.semantic.entity/model/entity.xcore#/EPackage/LEntityAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDtoReference" eSuperTypes="#//LDtoFeature ../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//LDto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedFeature" eType="ecore:EClass ../../org.lunifera.dsl.semantic.entity/model/entity.xcore#/EPackage/LEntityReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDtoOperation" eSuperTypes="../../org.lunifera.dsl.semantic.common/model/types.xcore#/EPackage/LOperation #//LDtoFeature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*&#xA;Overwrites LOperation to add dto feature as supertype"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DtoFeatureList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.dto.LDtoFeature>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="OperationsList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.dto.LDtoOperation>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DtoReferenceList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.dto.LDtoReference>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DtoAttributeList" instanceTypeName="java.util.List&lt;org.lunifera.dsl.semantic.dto.LDtoAttribute>"/>
</ecore:EPackage>
