/**
 * Copyright (c) 2011 - 2012, Florian Pirchner - lunifera.org
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Sources generated by Xtext  
 * 
 * Contributors:
 *  		Hans Georg Glöckler - Initial implementation
 *  		Florian Pirchner - Initial implementation
 */
package org.lunifera.dsl.entity.semantic.model;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LData Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LDataType#getJvmTypeReference <em>Jvm Type Reference</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLDataType()
 * @model
 * @generated
 */
public interface LDataType extends LScalarType {
	/**
	 * Returns the value of the '<em><b>Jvm Type Reference</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Jvm Type Reference</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Jvm Type Reference</em>' containment reference.
	 * @see #setJvmTypeReference(JvmTypeReference)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLDataType_JvmTypeReference()
	 * @model containment="true" required="true"
	 * @generated
	 */
	JvmTypeReference getJvmTypeReference();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LDataType#getJvmTypeReference <em>Jvm Type Reference</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Jvm Type Reference</em>' containment reference.
	 * @see #getJvmTypeReference()
	 * @generated
	 */
	void setJvmTypeReference(JvmTypeReference value);

} // LDataType
