/**
 * Copyright (c) 2011 - 2012, Florian Pirchner - lunifera.org
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Sources generated by Xtext  
 * 
 * Contributors:
 *  		Hans Georg Glöckler - Initial implementation
 *  		Florian Pirchner - Initial implementation
 */
package org.lunifera.dsl.entity.semantic.model;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LEntity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LEntity#getPersistenceName <em>Persistence Name</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LEntity#isCacheable <em>Cacheable</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LEntity#isHistorized <em>Historized</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LEntity#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LEntity#getOperations <em>Operations</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLEntity()
 * @model
 * @generated
 */
public interface LEntity extends LClass {
	/**
	 * Returns the value of the '<em><b>Persistence Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Persistence Name</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Persistence Name</em>' attribute.
	 * @see #setPersistenceName(String)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLEntity_PersistenceName()
	 * @model
	 * @generated
	 */
	String getPersistenceName();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LEntity#getPersistenceName <em>Persistence Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Persistence Name</em>' attribute.
	 * @see #getPersistenceName()
	 * @generated
	 */
	void setPersistenceName(String value);

	/**
	 * Returns the value of the '<em><b>Cacheable</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Cacheable</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Cacheable</em>' attribute.
	 * @see #setCacheable(boolean)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLEntity_Cacheable()
	 * @model unique="false"
	 * @generated
	 */
	boolean isCacheable();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LEntity#isCacheable <em>Cacheable</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Cacheable</em>' attribute.
	 * @see #isCacheable()
	 * @generated
	 */
	void setCacheable(boolean value);

	/**
	 * Returns the value of the '<em><b>Historized</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Historized</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Historized</em>' attribute.
	 * @see #setHistorized(boolean)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLEntity_Historized()
	 * @model unique="false"
	 * @generated
	 */
	boolean isHistorized();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LEntity#isHistorized <em>Historized</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Historized</em>' attribute.
	 * @see #isHistorized()
	 * @generated
	 */
	void setHistorized(boolean value);

	/**
	 * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
	 * The list contents are of type {@link org.lunifera.dsl.entity.semantic.model.LEntityProp}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Properties</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Properties</em>' containment reference list.
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLEntity_Properties()
	 * @model containment="true"
	 * @generated
	 */
	EList<LEntityProp> getProperties();

	/**
	 * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
	 * The list contents are of type {@link org.lunifera.dsl.entity.semantic.model.LOperation}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Operations</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Operations</em>' containment reference list.
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLEntity_Operations()
	 * @model containment="true"
	 * @generated
	 */
	EList<LOperation> getOperations();

	/**
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Super Type</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @model kind="operation"
	 * @generated
	 */
	LEntity getSuperType();

} // LEntity
