/**
 * Copyright (c) 2011 - 2012, Florian Pirchner - lunifera.org
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Sources generated by Xtext  
 * 
 * Contributors:
 *  		Hans Georg Glöckler - Initial implementation
 *  		Florian Pirchner - Initial implementation
 */
package org.lunifera.dsl.entity.semantic.model;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LMultiplicity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LMultiplicity#getLower <em>Lower</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LMultiplicity#getUpper <em>Upper</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLMultiplicity()
 * @model
 * @generated
 */
public interface LMultiplicity extends EObject {
	/**
	 * Returns the value of the '<em><b>Lower</b></em>' attribute.
	 * The literals are from the enumeration {@link org.lunifera.dsl.entity.semantic.model.LowerBound}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Lower</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Lower</em>' attribute.
	 * @see org.lunifera.dsl.entity.semantic.model.LowerBound
	 * @see #setLower(LowerBound)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLMultiplicity_Lower()
	 * @model
	 * @generated
	 */
	LowerBound getLower();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LMultiplicity#getLower <em>Lower</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Lower</em>' attribute.
	 * @see org.lunifera.dsl.entity.semantic.model.LowerBound
	 * @see #getLower()
	 * @generated
	 */
	void setLower(LowerBound value);

	/**
	 * Returns the value of the '<em><b>Upper</b></em>' attribute.
	 * The literals are from the enumeration {@link org.lunifera.dsl.entity.semantic.model.UpperBound}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Upper</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Upper</em>' attribute.
	 * @see org.lunifera.dsl.entity.semantic.model.UpperBound
	 * @see #setUpper(UpperBound)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLMultiplicity_Upper()
	 * @model
	 * @generated
	 */
	UpperBound getUpper();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LMultiplicity#getUpper <em>Upper</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Upper</em>' attribute.
	 * @see org.lunifera.dsl.entity.semantic.model.UpperBound
	 * @see #getUpper()
	 * @generated
	 */
	void setUpper(UpperBound value);

} // LMultiplicity
