/**
 * Copyright (c) 2011 - 2013, Committers of lunifera.org
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Sources generated by Xtext  
 * 
 * Contributors:
 *  		Hans Georg Glöckler - Initial implementation
 *  		Florian Pirchner - Initial implementation
 */
package org.lunifera.dsl.entity.semantic.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LPersistent Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LPersistentProperty#getPersistenceName <em>Persistence Name</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LPersistentProperty#isLazy <em>Lazy</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLPersistentProperty()
 * @model
 * @generated
 */
public interface LPersistentProperty extends LProperty {
	/**
	 * Returns the value of the '<em><b>Persistence Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Persistence Name</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Persistence Name</em>' attribute.
	 * @see #setPersistenceName(String)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLPersistentProperty_PersistenceName()
	 * @model
	 * @generated
	 */
	String getPersistenceName();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LPersistentProperty#getPersistenceName <em>Persistence Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Persistence Name</em>' attribute.
	 * @see #getPersistenceName()
	 * @generated
	 */
	void setPersistenceName(String value);

	/**
	 * Returns the value of the '<em><b>Lazy</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Lazy</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Lazy</em>' attribute.
	 * @see #setLazy(boolean)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLPersistentProperty_Lazy()
	 * @model
	 * @generated
	 */
	boolean isLazy();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LPersistentProperty#isLazy <em>Lazy</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Lazy</em>' attribute.
	 * @see #isLazy()
	 * @generated
	 */
	void setLazy(boolean value);

} // LPersistentProperty
