/**
 * Copyright (c) 2011 - 2012, Florian Pirchner - lunifera.org
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Sources generated by Xtext  
 * 
 * Contributors:
 *  		Hans Georg Glöckler - Initial implementation
 *  		Florian Pirchner - Initial implementation
 */
package org.lunifera.dsl.entity.semantic.model;

import org.eclipse.xtext.common.types.JvmTypeReference;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LProperty</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#getName <em>Name</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#getType <em>Type</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#getJvmTypeRef <em>Jvm Type Ref</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#isId <em>Id</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#isVersion <em>Version</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#isNotnull <em>Notnull</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#isTransient <em>Transient</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#getDefaultValueLiteral <em>Default Value Literal</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#getLower <em>Lower</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#getUpper <em>Upper</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#isCollection <em>Collection</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#isComposition <em>Composition</em>}</li>
 *   <li>{@link org.lunifera.dsl.entity.semantic.model.LProperty#getOpposite <em>Opposite</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty()
 * @model
 * @generated
 */
public interface LProperty extends LAnnotationTarget {
	/**
	 * Returns the value of the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Id</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Id</em>' attribute.
	 * @see #setId(boolean)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Id()
	 * @model
	 * @generated
	 */
	boolean isId();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#isId <em>Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Id</em>' attribute.
	 * @see #isId()
	 * @generated
	 */
	void setId(boolean value);

	/**
	 * Returns the value of the '<em><b>Version</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Version</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Version</em>' attribute.
	 * @see #setVersion(boolean)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Version()
	 * @model
	 * @generated
	 */
	boolean isVersion();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#isVersion <em>Version</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Version</em>' attribute.
	 * @see #isVersion()
	 * @generated
	 */
	void setVersion(boolean value);

	/**
	 * Returns the value of the '<em><b>Notnull</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Notnull</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Notnull</em>' attribute.
	 * @see #setNotnull(boolean)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Notnull()
	 * @model
	 * @generated
	 */
	boolean isNotnull();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#isNotnull <em>Notnull</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Notnull</em>' attribute.
	 * @see #isNotnull()
	 * @generated
	 */
	void setNotnull(boolean value);

	/**
	 * Returns the value of the '<em><b>Transient</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Transient</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Transient</em>' attribute.
	 * @see #setTransient(boolean)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Transient()
	 * @model
	 * @generated
	 */
	boolean isTransient();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#isTransient <em>Transient</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Transient</em>' attribute.
	 * @see #isTransient()
	 * @generated
	 */
	void setTransient(boolean value);

	/**
	 * Returns the value of the '<em><b>Default Value Literal</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Default Value Literal</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Default Value Literal</em>' attribute.
	 * @see #setDefaultValueLiteral(String)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_DefaultValueLiteral()
	 * @model
	 * @generated
	 */
	String getDefaultValueLiteral();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#getDefaultValueLiteral <em>Default Value Literal</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Default Value Literal</em>' attribute.
	 * @see #getDefaultValueLiteral()
	 * @generated
	 */
	void setDefaultValueLiteral(String value);

	/**
	 * Returns the value of the '<em><b>Lower</b></em>' attribute.
	 * The literals are from the enumeration {@link org.lunifera.dsl.entity.semantic.model.LowerBound}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Lower</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Lower</em>' attribute.
	 * @see org.lunifera.dsl.entity.semantic.model.LowerBound
	 * @see #setLower(LowerBound)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Lower()
	 * @model
	 * @generated
	 */
	LowerBound getLower();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#getLower <em>Lower</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Lower</em>' attribute.
	 * @see org.lunifera.dsl.entity.semantic.model.LowerBound
	 * @see #getLower()
	 * @generated
	 */
	void setLower(LowerBound value);

	/**
	 * Returns the value of the '<em><b>Upper</b></em>' attribute.
	 * The literals are from the enumeration {@link org.lunifera.dsl.entity.semantic.model.UpperBound}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Upper</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Upper</em>' attribute.
	 * @see org.lunifera.dsl.entity.semantic.model.UpperBound
	 * @see #setUpper(UpperBound)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Upper()
	 * @model
	 * @generated
	 */
	UpperBound getUpper();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#getUpper <em>Upper</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Upper</em>' attribute.
	 * @see org.lunifera.dsl.entity.semantic.model.UpperBound
	 * @see #getUpper()
	 * @generated
	 */
	void setUpper(UpperBound value);

	/**
	 * Returns the value of the '<em><b>Collection</b></em>' attribute.
	 * The default value is <code>"false"</code>.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Collection</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Collection</em>' attribute.
	 * @see #setCollection(boolean)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Collection()
	 * @model default="false"
	 * @generated
	 */
	boolean isCollection();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#isCollection <em>Collection</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Collection</em>' attribute.
	 * @see #isCollection()
	 * @generated
	 */
	void setCollection(boolean value);

	/**
	 * Returns the value of the '<em><b>Composition</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Composition</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Composition</em>' attribute.
	 * @see #setComposition(boolean)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Composition()
	 * @model
	 * @generated
	 */
	boolean isComposition();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#isComposition <em>Composition</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Composition</em>' attribute.
	 * @see #isComposition()
	 * @generated
	 */
	void setComposition(boolean value);

	/**
	 * Returns the value of the '<em><b>Opposite</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Opposite</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Opposite</em>' reference.
	 * @see #setOpposite(LProperty)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Opposite()
	 * @model
	 * @generated
	 */
	LProperty getOpposite();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#getOpposite <em>Opposite</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Opposite</em>' reference.
	 * @see #getOpposite()
	 * @generated
	 */
	void setOpposite(LProperty value);

	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Name</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Type</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Type</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Type</em>' reference.
	 * @see #setType(LType)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_Type()
	 * @model
	 * @generated
	 */
	LType getType();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#getType <em>Type</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Type</em>' reference.
	 * @see #getType()
	 * @generated
	 */
	void setType(LType value);

	/**
	 * Returns the value of the '<em><b>Jvm Type Ref</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Jvm Type Ref</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Jvm Type Ref</em>' containment reference.
	 * @see #setJvmTypeRef(JvmTypeReference)
	 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLProperty_JvmTypeRef()
	 * @model containment="true"
	 * @generated
	 */
	JvmTypeReference getJvmTypeRef();

	/**
	 * Sets the value of the '{@link org.lunifera.dsl.entity.semantic.model.LProperty#getJvmTypeRef <em>Jvm Type Ref</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Jvm Type Ref</em>' containment reference.
	 * @see #getJvmTypeRef()
	 * @generated
	 */
	void setJvmTypeRef(JvmTypeReference value);

} // LProperty
