/**
 * Copyright (c) 2011 - 2013, Committers of lunifera.org
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Sources generated by Xtext  
 * 
 * Contributors:
 *  		Hans Georg Glöckler - Initial implementation
 *  		Florian Pirchner - Initial implementation
 */
package org.lunifera.dsl.entity.semantic.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LScalar Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.lunifera.dsl.entity.semantic.model.EntityPackage#getLScalarType()
 * @model
 * @generated
 */
public interface LScalarType extends LType {
} // LScalarType
