grammar org.lunifera.dsl.component.xtext.ComponentGrammar with org.eclipse.xtext.xbase.Xbase


import "http://www.lunifera.org/dsl/component/v1"
import "http://www.eclipse.org/emf/2002/Ecore"
import "http://www.eclipse.org/emf/2002/GenModel" as genmodel
import "http://www.eclipse.org/xtext/xbase/Xbase" as xbase
import "http://www.eclipse.org/xtext/common/JavaVMTypes" as types

ComponentModel: 
	unitTypes+=UnitType
;

UnitType:
	'name' name=ID 
;